# Generated by Django 5.0.4 on 2024-04-14 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='proveedor',
            table='proveedores',
        ),
    ]
