# Generated by Django 5.0.4 on 2024-06-18 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='beneficios_producto',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_producto',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_producto',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='tamano_producto',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coleccion',
            name='nombre_coleccion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='producto',
            name='coleccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='tienda.coleccion'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre_producto',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_producto',
            field=models.FloatField(default=0.0),
        ),
    ]
