# Generated by Django 5.0.4 on 2024-04-14 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_proveedor_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='proveedor',
            table=None,
        ),
    ]
