# Generated by Django 5.0.4 on 2024-04-26 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_coleccion_producto_coleccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterModelOptions(
            name='coleccion',
            options={'verbose_name': 'Coleccion', 'verbose_name_plural': 'Colecciones'},
        ),
        migrations.RemoveField(
            model_name='producto',
            name='canales_de_ventas',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='mercados',
        ),
        migrations.AlterModelTable(
            name='coleccion',
            table='tienda_coleccion',
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estatus_pago', models.CharField(choices=[('pagado', 'Pagado'), ('no_pagado', 'No pagado')], max_length=20)),
                ('estatus_pedido', models.CharField(max_length=20)),
                ('items', models.IntegerField()),
                ('estatus_entrega', models.CharField(max_length=20)),
                ('forma_entrega', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='tienda.cliente')),
            ],
        ),
    ]
