# Generated by Django 5.0.4 on 2024-04-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_cliente_alter_coleccion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='id',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estatus_entrega',
            field=models.CharField(choices=[('entregado', 'Entregado'), ('no_entregado', 'No entregado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estatus_pedido',
            field=models.CharField(choices=[('procesado', 'Procesado'), ('no_procesado', 'No procesado')], max_length=20),
        ),
    ]
