# Generated by Django 5.0.4 on 2024-05-01 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_remove_pedido_id_alter_pedido_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='coleccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.coleccion'),
        ),
    ]
