# Generated by Django 5.0.4 on 2024-05-01 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_alter_producto_coleccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='coleccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.coleccion'),
        ),
    ]
