# Generated by Django 5.0.4 on 2024-05-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_alter_producto_coleccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
        migrations.AlterField(
            model_name='producto',
            name='status',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('ARCHIVADO', 'ARCHIVADO')], max_length=20),
        ),
    ]
