# Generated by Django 5.0.4 on 2024-05-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0012_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='forma_entrega',
            field=models.CharField(choices=[('correosPac', 'Correos PAC'), ('pedidosYa', 'Pedidos Ya')], max_length=100),
        ),
    ]
